/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    media: Media;
    products: Product;
    'no-store-products': NoStoreProduct;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    header: Header;
    footer: Footer;
    regulamin: Regulamin;
    'landing-page': LandingPage;
    'products-page': ProductsPage;
    appSettings: AppSetting;
    aboutPage: AboutPage;
    contactPage: ContactPage;
    thesis: Thesis;
    deliveryOptions: DeliveryOption;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'user';
  fullName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  title: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    avatar?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  slug?: string | null;
  productInfo: {
    productImage: string | Media;
    productName: string;
    productShortDescription: string;
    basePrice: number;
    productLongDescription?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    productLongDescriptionHTML?: string | null;
  };
  productSpecs?:
    | {
        specName: string;
        specDisplayName: string;
        specDesc: string;
        specValues: {
          name: string;
          desc: string;
          priceModifier?: number | null;
          priceMultiplier?: number | null;
          conditionalModifiers?:
            | {
                dependsOn: string;
                whenValue: string;
                priceModifier?: number | null;
                priceMultiplier?: number | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "no-store-products".
 */
export interface NoStoreProduct {
  id: string;
  slug?: string | null;
  productInfo: {
    productImage: string | Media;
    productName: string;
    productShortDescription: string;
    productLongDescription?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    productLongDescriptionHTML?: string | null;
  };
  productSpecs?:
    | {
        specName: string;
        specDisplayName: string;
        specDesc: string;
        specValues: {
          name: string;
          desc: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo: {
    mainLogoFile: string | Media;
    mainLogoWidth?: number | null;
    mobileLogoFile: string | Media;
    mobileLogoWidth?: number | null;
    id?: string | null;
  }[];
  infoBar: {
    infoBarText: string;
    infoBarImage?: string | Media | null;
    id?: string | null;
  }[];
  phoneNums?:
    | {
        phoneNum: string;
        id?: string | null;
      }[]
    | null;
  contactUsAddress: string;
  headerLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: string | null;
          url?: string | null;
          label: string;
          isDisabled?: boolean | null;
          isHidden?: boolean | null;
          appearance?: ('default' | 'simple-button' | 'special-button') | null;
          size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
          color?: ('black' | 'primary' | 'white') | null;
          variant?: ('solid' | 'outline' | 'soft' | 'ghost') | null;
          icon?: string | null;
          iconPosition?: ('left' | 'right') | null;
          iconMovementDirection?: ('down' | 'up' | 'right' | 'left') | null;
        };
        id?: string | null;
      }[]
    | null;
  headerLinksRightSide?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: string | null;
          url?: string | null;
          label: string;
          isDisabled?: boolean | null;
          isHidden?: boolean | null;
          appearance?: ('default' | 'simple-button' | 'special-button') | null;
          size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
          color?: ('black' | 'primary' | 'white') | null;
          variant?: ('solid' | 'outline' | 'soft' | 'ghost') | null;
          icon?: string | null;
          iconPosition?: ('left' | 'right') | null;
          iconMovementDirection?: ('down' | 'up' | 'right' | 'left') | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  logo: string | Media;
  footerHero?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  footerHeroHTML?: string | null;
  openingHours?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  openingHoursHTML?: string | null;
  phoneNums?:
    | {
        phoneNum: string;
        id?: string | null;
      }[]
    | null;
  contactUsAddress: string;
  legalNote: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulamin".
 */
export interface Regulamin {
  id: string;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentHTML?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | Media | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page".
 */
export interface LandingPage {
  id: string;
  heroBadge: {
    text: string;
    icon?: string | null;
    variant: 'transparent' | 'white';
  };
  landingHero: string;
  landingHeroLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: string | null;
          url?: string | null;
          label: string;
          isDisabled?: boolean | null;
          isHidden?: boolean | null;
          appearance?: ('default' | 'simple-button' | 'special-button') | null;
          size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
          color?: ('black' | 'primary' | 'white') | null;
          variant?: ('solid' | 'outline' | 'soft' | 'ghost') | null;
          icon?: string | null;
          iconPosition?: ('left' | 'right') | null;
          iconMovementDirection?: ('down' | 'up' | 'right' | 'left') | null;
        };
        id?: string | null;
      }[]
    | null;
  servicesBadge: {
    text: string;
    icon?: string | null;
    variant: 'transparent' | 'white';
  };
  servicesText: {
    header: string;
    paragraph: string;
    topLabel?: string | null;
    ctaHeader: string;
    ctaParagraph: string;
    id?: string | null;
  }[];
  servicesSections: {
    mediaType: 'image' | 'icon';
    serviceImg?: string | Media | null;
    iconId?: string | null;
    sectionHeader?: string | null;
    sectionParagraph?: string | null;
    link: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?: string | null;
      url?: string | null;
      label: string;
      isDisabled?: boolean | null;
      isHidden?: boolean | null;
      appearance?: ('default' | 'simple-button' | 'special-button') | null;
      size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
      color?: ('black' | 'primary' | 'white') | null;
      variant?: ('solid' | 'outline' | 'soft' | 'ghost') | null;
      icon?: string | null;
      iconPosition?: ('left' | 'right') | null;
      iconMovementDirection?: ('down' | 'up' | 'right' | 'left') | null;
    };
    id?: string | null;
  }[];
  servicesCtaBadge: {
    text: string;
    icon?: string | null;
    variant: 'transparent' | 'white';
  };
  servicesLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: string | null;
          url?: string | null;
          label: string;
          isDisabled?: boolean | null;
          isHidden?: boolean | null;
          appearance?: ('default' | 'simple-button' | 'special-button') | null;
          size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
          color?: ('black' | 'primary' | 'white') | null;
          variant?: ('solid' | 'outline' | 'soft' | 'ghost') | null;
          icon?: string | null;
          iconPosition?: ('left' | 'right') | null;
          iconMovementDirection?: ('down' | 'up' | 'right' | 'left') | null;
        };
        id?: string | null;
      }[]
    | null;
  trustedUsBadge: {
    text: string;
    icon?: string | null;
    variant: 'transparent' | 'white';
  };
  zaufaliNamText: {
    header: string;
    paragraph: string;
    topLabel?: string | null;
    strong?: string | null;
    id?: string | null;
  }[];
  zaufaliNamLogos?:
    | {
        logo: string | Media;
        id?: string | null;
      }[]
    | null;
  trustedUsLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: string | null;
          url?: string | null;
          label: string;
          isDisabled?: boolean | null;
          isHidden?: boolean | null;
          appearance?: ('default' | 'simple-button' | 'special-button') | null;
          size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
          color?: ('black' | 'primary' | 'white') | null;
          variant?: ('solid' | 'outline' | 'soft' | 'ghost') | null;
          icon?: string | null;
          iconPosition?: ('left' | 'right') | null;
          iconMovementDirection?: ('down' | 'up' | 'right' | 'left') | null;
        };
        id?: string | null;
      }[]
    | null;
  conversionBadge: {
    text: string;
    icon?: string | null;
    variant: 'transparent' | 'white';
  };
  konwersjaMarketingowaText: {
    header: string;
    paragraph: string;
    topLabel?: string | null;
    ctaParagraph: string;
    id?: string | null;
  }[];
  conversionLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: string | null;
          url?: string | null;
          label: string;
          isDisabled?: boolean | null;
          isHidden?: boolean | null;
          appearance?: ('default' | 'simple-button' | 'special-button') | null;
          size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
          color?: ('black' | 'primary' | 'white') | null;
          variant?: ('solid' | 'outline' | 'soft' | 'ghost') | null;
          icon?: string | null;
          iconPosition?: ('left' | 'right') | null;
          iconMovementDirection?: ('down' | 'up' | 'right' | 'left') | null;
        };
        id?: string | null;
      }[]
    | null;
  opinieKlientowText: {
    header: string;
    paragraph: string;
    topLabel?: string | null;
    strong?: string | null;
    id?: string | null;
  }[];
  mapBadge: {
    text: string;
    icon?: string | null;
    variant: 'transparent' | 'white';
  };
  mapaDojazduText: {
    header: string;
    paragraph: string;
    topLabel?: string | null;
    strong?: string | null;
    id?: string | null;
  }[];
  thesisBadge: {
    text: string;
    icon?: string | null;
    variant: 'transparent' | 'white';
  };
  pracaDyplomowaText: {
    header: string;
    paragraph: string;
    topLabel?: string | null;
    strong?: string | null;
    specPoints?:
      | {
          specPoint?: string | null;
          id?: string | null;
        }[]
      | null;
    productBadge: string;
    bottomSpecs: {
      leftBottomSpec: {
        leftBottomSpecText: string;
        leftBottomSpecIcon?: string | null;
      };
      rightBottomSpec: {
        rightBottomSpecText: string;
        rightBottomSpecIcon?: string | null;
      };
    };
    id?: string | null;
  }[];
  thesisButtons?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: string | null;
          url?: string | null;
          label: string;
          isDisabled?: boolean | null;
          isHidden?: boolean | null;
          appearance?: 'thesis-button' | null;
          size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
          color?: ('black' | 'primary' | 'white') | null;
          variant?: ('solid' | 'outline' | 'soft' | 'ghost') | null;
          icon?: string | null;
          iconPosition?: ('left' | 'right') | null;
          iconMovementDirection?: ('down' | 'up' | 'right' | 'left') | null;
        };
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | Media | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-page".
 */
export interface ProductsPage {
  id: string;
  productsTitle: string;
  productsParagraph: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appSettings".
 */
export interface AppSetting {
  id: string;
  orderEmails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  pageList: {
    pageName?: string | null;
    pageSlug?: string | null;
    id?: string | null;
  }[];
  availableDeliveryServices?:
    | {
        name: string;
        displayName: string;
        logo: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage".
 */
export interface AboutPage {
  id: string;
  topSection: {
    header: string;
    paragraph: string;
    mainImage: string | Media;
  };
  timelineSection: {
    items: {
      year: string;
      title: string;
      description: string;
      image: string | Media;
      id?: string | null;
    }[];
  };
  ctaSection: {
    header: string;
    paragraph: string;
    content: string;
    primaryButton: {
      label: string;
      url: string;
    };
    secondaryButton: {
      label: string;
      url: string;
    };
    phoneNumber: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: string | Media | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPage".
 */
export interface ContactPage {
  id: string;
  oferta: {
    title: string;
    description?: string | null;
    cards: {
      header: string;
      paragraph: string;
      icon: string;
      id?: string | null;
    }[];
  };
  zespol: {
    title: string;
    description?: string | null;
    cards: {
      name: string;
      position: string;
      description?: string | null;
      email: string;
      phoneNumber: string;
      photo: string | Media;
      id?: string | null;
    }[];
  };
  cta: {
    title: string;
    description?: string | null;
    buttonLabel: string;
    buttonEmail: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "thesis".
 */
export interface Thesis {
  id: string;
  productInfo: {
    productImage: string | Media;
    productName: string;
    productShortDescription: string;
    basePrice: number;
    productLongDescription?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    productLongDescriptionHTML?: string | null;
  };
  productSpecs?:
    | {
        specName: string;
        specDisplayName: string;
        specDesc: string;
        specValues: {
          name: string;
          desc: string;
          priceModifier?: number | null;
          priceMultiplier?: number | null;
          conditionalModifiers?:
            | {
                dependsOn: string;
                whenValue: string;
                priceModifier?: number | null;
                priceMultiplier?: number | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deliveryOptions".
 */
export interface DeliveryOption {
  id: string;
  options?:
    | {
        name: string;
        description: string;
        price: number;
        time?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}

